### ISSUE TITLE
VITS Japanese模型训练报错

### ISSUE THREAD

**Issue by QuellaMC** [CjangCjengh/MoeGoe#10]
/content/vits/utils.py:134: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
INFO:zerot:Saving model and optimizer state at iteration 1 to ../drive/MyDrive/zerot/G_0.pth
INFO:zerot:Saving model and optimizer state at iteration 1 to ../drive/MyDrive/zerot/D_0.pth
Traceback (most recent call last):
  File "train_ms.py", line 299, in <module>
    main()
  File "train_ms.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/content/vits/train_ms.py", line 123, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/vits/train_ms.py", line 151, in train_and_evaluate
    (z, z_p, m_p, logs_p, m_q, logs_q) = net_g(x, x_lengths, spec, spec_lengths, speakers)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/vits/models.py", line 495, in forward
    z_slice, ids_slice = commons.rand_slice_segments(z, y_lengths, self.segment_size)
  File "/content/vits/commons.py", line 63, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "/content/vits/commons.py", line 53, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (32) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 32].  Tensor sizes: [192, 0]

我自己提取的wav文件进行训练，结果发现程序报错，自己尝试解决但是没有成功，希望大佬能帮忙解决一下。

**Comment by CjangCjengh** [comment]
音频过短

**Comment by QuellaMC** [comment]
请问大概多长的音频比较合适？

**Comment by CjangCjengh** [comment]
>0.35s

**Comment by QuellaMC** [comment]
了解，谢谢大佬解答疑惑！
