### ISSUE TITLE
Required to update numpy version dependency

### ISSUE THREAD

**Issue by RyaoChengfeng** [CjangCjengh/MoeGoe#52]
In the `requirements.txt` file, `numpy==1.22.0` is specified. However, when running MoeGoe.py on my computer, I encountered a `RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf.`

I was able to resolve the issue by using `pip install --upgrade numpy` to update numpy to **1.24.3**.

Python version: **Python 3.10.10**

I'm not familiar with Python conventions, but perhaps we should consider specifying the package versions in `requirements.txt`? 

Here are full execution process:
```bash
(venv)
$ pip install -r requirements.txt
...
$ python MoeGoe.py
Path of a VITS model: ./G_latest.pth
Path of a config file: ./config.json
TTS or VC? (t/v): t
Text to read: [JA]こんにちは。[JA]

Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf. Check the section C-API incompatibility at the Troubleshooting ImportError section at [link](https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility) for indications on how to solve this problem.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/MoeGoe/MoeGoe.py", line 152, in <module>
    stn_tst = get_text(text, hps_ms, cleaned=cleaned)
  File "/MoeGoe/MoeGoe.py", line 26, in get_text
    text_norm = text_to_sequence(text, hps.symbols, hps.data.text_cleaners)
  File "/MoeGoe/text/__init__.py", line 17, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "/MoeGoe/text/__init__.py", line 31, in _clean_text
    text = cleaner(text)
  File "/MoeGoe/text/cleaners.py", line 37, in zh_ja_mixture_cleaners
    from text.japanese import japanese_to_romaji_with_accent
  File "/MoeGoe/text/japanese.py", line 3, in <module>
    import pyopenjtalk
  File "/MoeGoe/venv/lib/python3.10/site-packages/pyopenjtalk/__init__.py", line 10, in <module>
    from pyopenjtalk.htsengine import HTSEngine
  File "pyopenjtalk/htsengine.pyx", line 10, in init pyopenjtalk.htsengine
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

**Comment by RyaoChengfeng** [comment]
#49 Well, this PR can fix it
